pipeline:
  build:
    image: plugins/docker
    repo: aong/app
    tags:
      - 2.5
      - latest
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
  kubectl:
    image: komljen/drone-kubectl-helm
    secrets: [ KUBERNETES_SERVER, KUBERNETES_CERT, KUBERNETES_TOKEN ]
    kubectl: "get pods"
  deploy:
    image: sh4d1/drone-kubernetes
    kubernetes_template: deployment.yml
    kubernetes_namespace: default
    secrets: [ KUBERNETES_SERVER, KUBERNETES_CERT, KUBERNETES_TOKEN ]
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=somsri_payroll_test
