pipeline:
  build:
    image: plugins/docker
    repo: bananacoding/banana-inventory
    tags:
      - 1.0.2
      - latest
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./bundler
    volumes:
      - /tmp/cache:/cache
  deploy:
    image: sh4d1/drone-kubernetes
    kubernetes_template: deployment.yml
    kubernetes_namespace: default
    secrets: [ KUBERNETES_SERVER, KUBERNETES_CERT, KUBERNETES_TOKEN ]
    when:
      branch: [ master ]
  notify:
    image: drillster/drone-email
    from: noreply-drone@bananacoding.com
    host: $EMAIL_HOST
    username: $EMAIL_USERNAME
    password: $EMAIL_PASSWORD
    recipients:
      - kraiwut@bananacoding.com
      - wiriya@bananacoding.com
      - tawan@bananacoding.com
      - jirapong@bananacoding.com
      - manit@bananacoding.com
      - sawakit@bananacoding.com
    secrets: [ EMAIL_HOST, EMAIL_USERNAME, EMAIL_PASSWORD ]
    when:
      status: [ success, failure ]

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=somsri_payroll_test
