version: '2'
services:
  app:
    build: .
    #command: bash -c "rm -rf tmp/pids && bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=mysecurepass
      - PDFTK_PATH=''
      - SENDGRID_USERNAME=''
      - SENDGRID_PASSWORD=''
      - BIND_ON=0.0.0.0:3000
      - RAILS_ENV=development
    volumes:
      - .:/app/somsri/payroll
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecurepass
      - POSTGRES_DB=rails-kube-demo_dev
      - PGDATA=/var/lib/postgresql/data
