version: '2'
services:
  app:
    build: .
    command: bash -c "rm -rf tmp/pids && bundle exec rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASS=pass
      - PDFTK_PATH=''
      - SENDGRID_USERNAME=''
      - SENDGRID_PASSWORD=''
      - BIND_ON=0.0.0.0:3000
      - RAILS_ENV=production
    volumes:
      - .:/app/somsri/payroll
  db:
    restart: always
    image: sameersbn/postgresql:9.4-21
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_NAME=somsri_payroll_dev
      - DB_USER=root
      - DB_PASS=pass
    volumes:
      - .:/var/lib/postgresql
