PDFTK_PATH: /usr/local/bin/pdftk
SENDGRID_USERNAME: somsri_dev
SENDGRID_PASSWORD: somsri_test
AWS_REGION: ap-southeast-1
S3_BUCKET_NAME: somsri-dev
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
BIND_ON: 3000
ENDPOINT: "localhost:3000"
OMISE_SECRET_KEY: skey_test_5gt4ctq58chozplemuw
OMISE_PUPLIC_KEY: pkey_test_5gt4ctq4y99u88fzsoy
DEFAULT_URL_MAILER_ON_PRODUCTION: www.bananahacking.com
EXCEPTIONNOTIFICATION: bananahacking.com
# TEAM_CONNECTOR_WEBHOOK_URL: 'https://outlook.office.com/webhook/43beed34-32d3-49bd-b06b-8e683e9148ea@c70ad7a7-3297-49cc-aa05-725ddcb5f870/IncomingWebhook/49f0fa076e4946f69d906d388500bce1/a951322e-7650-443a-9a2f-5870fd9c6073'

production:
  PDFTK_PATH: /usr/local/bin/pdftk
  SECRET_KEY_BASE: cbe5e6a781bd3fe930158b527e5dc6ffab68a329fe948fefd5e935e78bd67470bef19b48b47c41389ae9803a7f578c7627f936d1ff2f15a6063f0a28c2124c5c
  S3_BUCKET_NAME: bankad-somsri
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION: ap-southeast-1
  SENTRY_KEY: "https://faab377947e64262931aebdeea6156f9@sentry.io/1422822"
