PDFTK_PATH: /usr/local/bin/pdftk
SENDGRID_USERNAME: somsri_dev
SENDGRID_PASSWORD: somsri_test
AWS_REGION: ap-southeast-1
S3_BUCKET_NAME: somsri-dev
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:

production:
 PDFTK_PATH: /usr/local/bin/pdftk
 SECRET_KEY_BASE: cbe5e6a781bd3fe930158b527e5dc6ffab68a329fe948fefd5e935e78bd67470bef19b48b47c41389ae9803a7f578c7627f936d1ff2f15a6063f0a28c2124c5c
 S3_BUCKET_NAME: bankad-somsri
 AWS_ACCESS_KEY_ID:
 AWS_SECRET_ACCESS_KEY:
 AWS_REGION: ap-southeast-1
