PDFTK_PATH: /usr/local/bin/pdftk
SENDGRID_USERNAME: somsri_dev
SENDGRID_PASSWORD: somsri_test
ROLLCALL_APK_URL: https://www.dropbox.com/s/luxeuq3g0byjgnn/Somsri-RollCall.apk?dl=0
AWS_REGION: ap-southeast-1
S3_BUCKET_NAME: somsri-dev
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
BIND_ON: 3000

production:
 PDFTK_PATH: /usr/local/bin/pdftk
 SECRET_KEY_BASE: cbe5e6a781bd3fe930158b527e5dc6ffab68a329fe948fefd5e935e78bd67470bef19b48b47c41389ae9803a7f578c7627f936d1ff2f15a6063f0a28c2124c5c
 S3_BUCKET_NAME: bankad-somsri
 ROLLCALL_APK_URL: https://www.dropbox.com/s/luxeuq3g0byjgnn/Somsri-RollCall.apk?dl=0
 AWS_ACCESS_KEY_ID:
 AWS_SECRET_ACCESS_KEY:
 AWS_REGION: ap-southeast-1
 SENTRY_KEY: 'https://faab377947e64262931aebdeea6156f9@sentry.io/1422822'