development:
  adapter: postgresql
  encoding: utf8
  database: somsri_payroll_dev
  pool: 5
  username: Pondpaun7z
  password: 7898

test:
  adapter: postgresql
  encoding: utf8
  database: somsri_payroll_test
  pool: 5
  username: Pondpaun7z
  password: 7898
