development:
  adapter: postgresql
  encoding: utf8
  database: somsri_payroll_dev
  pool: 5
  username: bom
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: somsri_payroll_test
  pool: 5
  username: bom
  password:
