common: &common
  :styles:
    :thumb: "100x100>"
    :medium: "300x300>"
  :default_url:


development:
  <<: *common

production:
  <<: *common
  :storage: :s3
  s3_credentials: {
    bucket: ENV.fetch('S3_BUCKET_NAME'),
    access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
    secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
    s3_region: ENV.fetch('AWS_REGION'),
  }

test:
  <<: *common
